post likes
pereslop/rails-new pull request #6
Opened 2017-09-29 12:39 UTC by pereslop

2017-09-29 14:16 UTC, Snick555 requested changes

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/account/users/confirmations_controller.rb
> +class Account::Users::ConfirmationsController < Devise::ConfirmationsController
why do you need this controller?

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/account/users/omniauth_callbacks_controller.rb
> +class Account::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
why do you need this controller?

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/account/users/passwords_controller.rb
> +class Account::Users::PasswordsController < Devise::PasswordsController
why do you need this controller?

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/account/users/registrations_controller.rb
> +class Account::Users::RegistrationsController < Devise::RegistrationsController
why do you need this controller?

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/account/users/unlocks_controller.rb
> +class Account::Users::UnlocksController < Devise::UnlocksController
why do you need this controller?

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/account/users/sessions_controller.rb
> +class Account::Users::SessionsController < Devise::SessionsController
Please remove all commented code

2017-09-29 14:16 UTC, Snick555 commented on app/controllers/home_controller.rb
> +  def collection
why do you need these empty methods?

2017-09-29 14:16 UTC, Snick555 commented on app/views/account/users/show.html.slim
> +    - if @user.username == current_user.username
Is username unique? What will be if another user with the same username come here?

2017-09-30 08:48 UTC, Snick555 commented
Please don't push local images.

2017-10-03 15:56 UTC, Snick555 requested changes

2017-10-03 15:56 UTC, Snick555 commented on app/controllers/home_controller.rb
> +    if user_signed_in?
please add `before_action :authenticate_user!`

2017-10-03 15:56 UTC, Snick555 commented on app/models/user.rb
> +   validates :username, :presence => true,
please use newest syntax `presence: true`

2017-10-03 15:56 UTC, Snick555 commented on db/migrate/20170929085339_create_likes.rb
> +    add_index :likes, ["liker_id", "liker_type"],       :name => "fk_likes"
why do you use rocket syntax?

2017-10-03 15:56 UTC, Snick555 commented on app/views/account/users/show.html.slim
> +      - if @user.email == current_user.email
please compare ids

2017-10-04 05:21 UTC, pereslop commented on db/migrate/20170929085339_create_likes.rb
> +    add_index :likes, ["liker_id", "liker_type"],       :name => "fk_likes"
I just copied it from github gem README

2017-10-04 08:02 UTC, Snick555 approved these changes

2017-10-04 08:02 UTC, merged